import { Film } from '../types/Film';

const films: Film[] = [
  {
    id: 1,
    name: '',
    slogan: '',
    ratings: [],
    age: '',
    originalName: '',
    poster: '',
    summary: '',
    trailer: [{ thumbnail: '', src: '' }],
    thumbnails: ['', '', ''],
    description: '',
    usersRating: 1,
    reviews: [''],
    genre: '',
    release: [''],
    audio: '',
    studio: [''],
    countries: '',
    actors: [],
    director: [],
    producers: [],
    facts: [],
    wins: '',
    type: 'film',
    filmSrc: '',
  },
  {
    id: 2,
    name: 'Опочтарение',
    slogan: 'Вам письмо!',
    ratings: [7.8, 7.7],
    age: '16+',
    originalName: 'Going Postal',
    poster: 'https://i.imgur.com/u0QyCmo.jpg',
    summary: '1 сезон / фэнтези, приключения, 2010',
    trailer: [{ thumbnail: 'https://pic.showjet.ru/pics/4440a521-5663-4d4e-8326-02bf205b665f/10x5/550.jpg', src: '' }],
    thumbnails: ['https://i.imgur.com/imKqvro.jpg', 'https://i.imgur.com/rea5SbN.jpg', 'https://i.imgur.com/583EUaK.jpg', 'https://i.imgur.com/qBnAEFW.jpg', 'https://i.imgur.com/jtAWyJm.jpg', 'https://i.imgur.com/KYKoPyY.jpg'],
    description: 'Добро пожаловать в воображариум Терри Пратчетта! \nМокрист фон Губвиг был гениальным мошенником: подделывал предметы искусства и мастерски обкрадывал людей — настоящий Остап Бендер в мире стимпанка. Однажды Мокриста всё-таки поймали и приговорили к смертной казни, но вместо исполнения приговора предложили сделку: восстановить работу единственного городского почтамта. \nВсё бы хорошо, но писем там скопилось просто тьма, а над самим почтамтом висит страшное проклятье: 4 предшественника Губвига погибли при очень странных обстоятельствах. Вдобавок ко всему у главного героя появляется неприятный конкурент — Взяткер Позолот.',
    usersRating: 5,
    reviews: [''],
    genre: 'фэнтези, приключения, мелодрама, детектив, комедия',
    release: ['30 мая 2010 г.', '30 мая 2010 г.'],
    audio: 'Английский, Русский',
    studio: ['Sky'],
    countries: 'Великобритания',
    actors: [{ personId: 1, role: 'Барабант' }, { personId: 2, role: 'Лорд Витинари' }, { personId: 3, role: 'Мисс Крипслок' }, { personId: 4, role: 'Мокрист фон Губвиг' }, { personId: 5, role: 'Мистер Грыль' }, { personId: 6, role: 'Взяткер Позолот' }, { personId: 7, role: 'Почтальон' }, { personId: 8, role: 'Стэнли' }, { personId: 9, role: 'Ангела Красота Добросерд' }],
    director: [{ personId: 10, role: 'Jon Jones' }],
    producers: [{ personId: 11, role: 'Rod Brown' }, { personId: 12, role: 'Vadim Jean' }, { personId: 13, role: 'Sue De Beauvoir' }, { personId: 14, role: 'Sarah Conroy' }],
    facts: ['Фильм снят по мотивам романа Терри Пратчетта «Опочтарение» (Going Postal, 2004)', 'Не будучи профессиональным актером, Терри Пратчетт испытал некоторые затруднения со своей ролью, которая заключалась в том, чтобы просто пройтись по комнате. По словам самого писателя, ему «понадобилось шесть дублей, чтобы справиться с этой непростой задачей».', 'Почтальон в последней сцене — Терри Пратчетт, автор книги.', 'Термин «опочтарение» (англ. going postal) применяется для обозначения актов массовых убийств, которые совершаются в порыве ярости или в состоянии эмоциональной нестабильности.'],
    wins: 'Телевизионная премия BAFTA: Лучшие визуальные эффекты',
    type: 'serial',
    serial: {
      seasonsQty: 1,
      seasons: [
        {
          seasonInfo: 'Сезон 1 / 2010',
          episodes: [{ name: 'Эпизод 1', thumbnail: 'https://pic.showjet.ru/pics/91b51c45-7915-4c7a-a3fc-8c9213eaab0e/10x7/400.jpg', src: '' }, { name: 'Эпизод 2', thumbnail: 'https://pic.showjet.ru/pics/ee3ce08e-c57c-463e-b3d5-0592358160d3/10x7/400.jpg', src: '' }, { name: 'Эпизод 3', thumbnail: 'https://pic.showjet.ru/pics/fb8f8a02-cc38-4aaa-bf5a-3365488f3a83/10x7/400.jpg', src: '' }, { name: 'Эпизод 4', thumbnail: 'https://pic.showjet.ru/pics/f4079f61-9e69-4664-950f-dc47917233b0/10x7/400.jpg', src: '' }],
        },
      ],
    },
  },
  {
    id: 3,
    name: 'Сын',
    slogan: 'В главной роли Пирс Броснан',
    ratings: [7.5, 6.8],
    age: '16+',
    originalName: 'The Son',
    poster: 'https://pic.showjet.ru/pics/c5f48991-e55c-44b4-991d-b15ee8f374d5/10x5/1250.jpg',
    summary: '2 сезона / вестерн, драма, 2017 - 2019',
    trailer: [{ thumbnail: 'https://pic.showjet.ru/pics/a6ba8fe9-96c4-4247-adf1-08a586b41fcd/10x5/550.jpg', src: '' }],
    thumbnails: ['https://pic.showjet.ru/pics/f57d97e2-4343-4190-ba62-e7b35f21aa13/10x7/1000.jpg', 'https://pic.showjet.ru/pics/bd46c3b8-d2ce-4467-b18d-76d820bd136c/10x7/1000.jpg', 'https://pic.showjet.ru/pics/90147cc5-81e0-4920-9525-b1a2859b30dd/10x7/1000.jpg', 'https://pic.showjet.ru/pics/095bf496-1b81-4a55-a7a3-1e01be77bf7f/10x7/1000.jpg', 'https://pic.showjet.ru/pics/6c6a7ceb-e19e-47b3-8fd5-9697e703de36/10x7/1000.jpg', 'https://pic.showjet.ru/pics/51961699-1ce6-4cea-a0d0-3656d908495e/10x7/1000.jpg'],
    description: 'Жестокий и эпический вестерн о становлении Америки, показанном через историю одной семьи. В главной роли — Пирс Броснан. \n1849 год, центральный Техас. Юный Илай Маккалоу попадает в плен к индейцам после того, как те ворвались в дом и безжалостно расправились с его сёстрами и матерью. Неопытный, но смелый парень учится выживать и договариваться с диким племенем. \n1915 год, южный Техас. Параллельно разворачивается история уже взрослого Илая Маккалоу в окружении детей и внуков. Властный и уважаемый глава семьи, он владеет ранчо и пытается отыскать нефть. Теперь вместо индейцев его главными врагами стали мексиканцы, которые вот-вот развяжут войну. Однако сын Илая, Пит, не готов мириться с жестокими методами отца и отпускает одного мексиканца, которого Маккалоу взяли в плен. Это грозит разрушить не только семейные узы, но и всю империю Илая Маккалоу, которую тот строил много лет...',
    usersRating: 5,
    reviews: [''],
    genre: 'вестерн, драма',
    release: ['08 апреля 2017 г.'],
    audio: 'Английский, Русский',
    studio: ['AMC Studios'],
    countries: 'Соединенные Штаты Америки',
    actors: [{ personId: 14, role: 'Элай Маккалоу' }, { personId: 15, role: 'Пит Маккалоу' }, { personId: 16, role: 'Мария Гарсия' }, { personId: 17, role: 'Тошауэй' }, { personId: 18, role: 'Салли Маккалоу' }, { personId: 19, role: 'Молодой Элай Маккалоу' }],
    director: [{ personId: 20, role: 'Tom Harper' }, { personId: 21, role: 'Tom Vaughan' }, { personId: 22, role: 'Ellen Kuras' }],
    producers: [{ personId: 23, role: 'Daniel C. Connolly' }, { personId: 24, role: 'Henry Bronchtein' }],
    facts: ['Сериал основан на одноимённом романе Филиппа Майера, который был опубликован в 2013 году.', 'Изначально планировалось, что главную роль сыграет Сэм Нил, однако из-за личных обстоятельств он отказался от участия.', 'Пирс Броснан не играл в сериалах свыше 30 лет — после работы в сериале «Ремингтон Стил» (1982-1987).'],
    type: 'serial',
    serial: {
      seasonsQty: 2,
      seasons: [
        {
          seasonInfo: 'Сезон 2 / 2019',
          episodes: [{ name: 'Нумунуу', thumbnail: 'https://pic.showjet.ru/pics/4b29fa99-d5d6-4a0b-8961-c303c8dfd4dc/10x7/400.jpg', src: '' }, { name: 'Десять долларов и ощипанный гусь', thumbnail: 'https://pic.showjet.ru/pics/4db1a856-346f-4169-bfe3-0ef37a4e3a96/10x7/400.jpg', src: '' }, { name: 'Слепой тигр', thumbnail: 'https://pic.showjet.ru/pics/f6a0943c-1338-492d-aa09-9003f246f5d5/10x7/400.jpg', src: '' }, { name: 'Оскальпированная собака', thumbnail: 'https://pic.showjet.ru/pics/e5293d71-6402-402d-aeb1-e56e8fb2f434/10x7/400.jpg', src: '' }, { name: 'Горячее масло', thumbnail: 'https://pic.showjet.ru/pics/8bef34f2-b1e8-425b-9485-ae55a67666cc/10x7/400.jpg', src: '' }, { name: 'Голубой свет', thumbnail: 'https://pic.showjet.ru/pics/32cefeef-a8f2-44c4-8edc-636bdd20ee90/10x7/400.jpg', src: '' }, { name: 'Кто-то взял лопату', thumbnail: 'https://pic.showjet.ru/pics/ed8c9aa6-23ec-47fb-825d-924c6971618a/10x7/400.jpg', src: '' }, { name: 'Все их обвинительные следы', thumbnail: 'https://pic.showjet.ru/pics/d18d3370-c8a7-43f4-b7da-b224d8047045/10x7/400.jpg', src: '' }, { name: 'Медведь', thumbnail: 'https://pic.showjet.ru/pics/2828829f-7c9f-4f1f-9fd4-f1525519604a/10x7/400.jpg', src: '' }, { name: 'Легенда', thumbnail: 'https://pic.showjet.ru/pics/6939ca8f-e8ba-464c-9c9a-cd0c24257542/10x7/400.jpg', src: '' }],
        },
        {
          seasonInfo: 'Сезон 1 / 2017',
          episodes: [{ name: 'Первый сын Техаса', thumbnail: 'https://pic.showjet.ru/pics/a00f09db-c2aa-4e01-a641-65480ad71301/10x7/400.jpg', src: '' }, { name: 'Сливовое дерево', thumbnail: 'https://pic.showjet.ru/pics/b7aba7f2-6805-46b3-867c-c3ebc1fe6c7c/10x7/400.jpg', src: '' }, { name: 'Вторая империя', thumbnail: 'https://pic.showjet.ru/pics/5ff4588a-7cc2-4ddc-86da-e95799ac46a5/10x7/400.jpg', src: '' }, { name: 'Песня смерти', thumbnail: 'https://pic.showjet.ru/pics/8bf58de5-79e9-4262-a1aa-4a88b879706c/10x7/400.jpg', src: '' }, { name: 'Никаких пленных', thumbnail: 'https://pic.showjet.ru/pics/4f17fb20-62d6-4746-a205-4ab51ce98401/10x7/400.jpg', src: '' }, { name: 'Охотник на буйволов', thumbnail: 'https://pic.showjet.ru/pics/99af408e-6c9a-46f2-9809-01d5d6bd7786/10x7/400.jpg', src: '' }, { name: 'Брачные узы', thumbnail: 'https://pic.showjet.ru/pics/0e377e3f-380d-4c92-bcff-89fe04257c55/10x7/400.jpg', src: '' }, { name: 'Медовая охота', thumbnail: 'https://pic.showjet.ru/pics/cf2ec742-6a20-4212-8c64-dd40fa605610/10x7/400.jpg', src: '' }, { name: 'Пророчество', thumbnail: 'https://pic.showjet.ru/pics/497eedd0-2953-4600-b348-0fcb4049bdc2/10x7/400.jpg', src: '' }, { name: 'Скальпы', thumbnail: 'https://pic.showjet.ru/pics/6f2f017b-5fab-48fd-b93d-7a0fa7a8f171/10x7/400.jpg', src: '' }],
        },
      ],
    },
  },
  {
    id: 4,
    name: 'Индийское лето',
    slogan: 'Любовь на закате империи',
    ratings: [7.2, 7],
    age: '16+',
    originalName: 'Indian Summers',
    poster: 'https://pic.showjet.ru/pics/ab191704-3437-4e09-80b3-cfb3d61c6467/10x5/1250.jpg',
    summary: '2 сезона / история, мелодрама, 2015 - 2016',
    trailer: [{ thumbnail: 'https://pic.showjet.ru/pics/121a0a7b-a56b-4ed5-aa7c-25a4c26f62a3/10x5/550.jpg', src: '' }],
    thumbnails: ['https://pic.showjet.ru/pics/278d3a15-9dd9-4fa2-a499-c9cc25796322/10x7/1000.jpg', 'https://pic.showjet.ru/pics/0cfc2e39-9dc0-489f-b66a-b6f5f7dcd807/10x7/1000.jpg', 'https://pic.showjet.ru/pics/cd318c1d-e3b1-4058-9c59-efac23c16965/10x7/1000.jpg', 'https://pic.showjet.ru/pics/5f2e456f-081b-4015-9db0-c98d4d2b63de/10x7/1000.jpg', 'https://pic.showjet.ru/pics/3a5f58d3-3ef6-4855-a7ce-b536e2a37af2/10x7/1000.jpg', 'https://pic.showjet.ru/pics/3b436cb2-1d88-40ef-8a6c-95844c1754e5/10x7/1000.jpg'],
    description: 'Жестокий и эпический вестерн о становлении Америки, показанном через историю одной семьи. В главной роли — Пирс Броснан. \n1849 год, центральный Техас. Юный Илай Маккалоу попадает в плен к индейцам после того, как те ворвались в дом и безжалостно расправились с его сёстрами и матерью. Неопытный, но смелый парень учится выживать и договариваться с диким племенем. \n1915 год, южный Техас. Параллельно разворачивается история уже взрослого Илая Маккалоу в окружении детей и внуков. Властный и уважаемый глава семьи, он владеет ранчо и пытается отыскать нефть. Теперь вместо индейцев его главными врагами стали мексиканцы, которые вот-вот развяжут войну. Однако сын Илая, Пит, не готов мириться с жестокими методами отца и отпускает одного мексиканца, которого Маккалоу взяли в плен. Это грозит разрушить не только семейные узы, но и всю империю Илая Маккалоу, которую тот строил много лет...',
    usersRating: 5,
    reviews: [''],
    genre: 'история, мелодрама, драма',
    release: ['15 февраля 2015 г.', '15 февраля 2015 г.'],
    audio: 'Английский, Русский',
    studio: ['British Broadcasting', 'Corporation (BBC) Television'],
    countries: 'Великобритания',
    actors: [{ personId: 25, role: 'Синтия' }, { personId: 26, role: 'Ральф Уилан' }, { personId: 27, role: 'Африн Делал' }, { personId: 28, role: 'Суни Далал' }],
    director: [],
    producers: [],
    facts: [],
    type: 'serial',
    serial: {
      seasonsQty: 2,
      seasons: [
        {
          seasonInfo: '',
          episodes: [{ name: 'Первый сын Техаса', thumbnail: '', src: '' }, { name: 'Сливовое дерево', thumbnail: '', src: '' }, { name: 'Вторая империя', thumbnail: '', src: '' }, { name: 'Песня смерти', thumbnail: '', src: '' }, { name: 'Никаких пленных', thumbnail: '', src: '' }, { name: 'Охотник на буйволов', thumbnail: '', src: '' }, { name: 'Брачные узы', thumbnail: '', src: '' }, { name: 'Медовая охота', thumbnail: '', src: '' }, { name: 'Пророчество', thumbnail: '', src: '' }, { name: 'Скальпы', thumbnail: '', src: '' }],
        },
        {
          seasonInfo: '',
          episodes: [{ name: 'Нумунуу', thumbnail: '', src: '' }, { name: 'Десять долларов и ощипанный гусь', thumbnail: '', src: '' }, { name: 'Слепой тигр', thumbnail: '', src: '' }, { name: 'Оскальпированная собака', thumbnail: '', src: '' }, { name: 'Горячее масло', thumbnail: '', src: '' }, { name: 'Голубой свет', thumbnail: '', src: '' }, { name: 'Кто-то взял лопату', thumbnail: '', src: '' }, { name: 'Все их обвинительные следы', thumbnail: '', src: '' }, { name: 'Медведь', thumbnail: '', src: '' }, { name: 'Легенда', thumbnail: '', src: '' }],
        },
      ],
    },
  },
];
export default films;
